### ISSUE TITLE
PG to BQ, CDC messes up format of JSONB columns, whereas initial load doesn't

### ISSUE THREAD

**Issue by saisrirampur** [PeerDB-io/peerdb#828]
### Setup steps in Postgres for JSONB
```
CREATE TABLE test_jsonb(id serial primary key, j jsonb);
INSERT INTO test_jsonb(j) VALUES ('{"isDemo":false}');
--Kick off mirror now and after initial load insert another row on Postgres
INSERT INTO test_jsonb(j) VALUES ('{"isDemo":false}');
```

### Data in BQ for JSONB
<img width="719" alt="Screen Shot 2023-12-14 at 7 19 48 PM" src="https://github.com/PeerDB-io/peerdb/assets/4652192/a842fee5-f359-4cde-8720-526f693a28da">

### Setup steps in Postgres for ARRAY
```
CREATE TABLE test_array(id serial primary key, t text[], i int[]);
INSERT INTO  test_array(t,i) VALUES ('{sai,krishna}'::text[],'{1,2}'::int[]);
--Kick off mirror now and after initial load insert another row on Postgres
INSERT INTO  test_array(t,i) VALUES ('{sai,krishna}'::text[],'{1,2}'::int[]);
```

### Data in BQ for JSONB

<img width="902" alt="Screen Shot 2023-12-14 at 8 25 09 PM" src="https://github.com/PeerDB-io/peerdb/assets/4652192/ba1bce5b-d0b4-48b1-af54-c0e52fe2ee5f">

**Comment by Amogh-Bharadwaj** [comment]
Fixed by #830

**Comment by iskakaushik** [comment]
re-opening this as @heavycrystal  mentioned that this is still an issue for SF.
